#ifndef SQ_PROTOCOL_H
#define SQ_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include <termios.h>
#include <sqlite3.h>

/* Magic number to verify packet integrity: "QUAK" */
#define SQ_MAGIC 0x5155414B
#define SQ_SOCKET_PATH "/tmp/shapequake.sock"

typedef struct sq_connection {
	int fd;
	bool is_running;
} sq_socket_handle_t;

/* State of the ShapeQuake node */
typedef enum {
	SQ_STATE_IDLE,      /* Terminal Node: Waiting for command */
	SQ_STATE_EXECUTING, /* Situation Node: Command running in PTY */
	SQ_STATE_EXITING    /* Shutdown sequence */
} sq_state_t;

/* Packet types for routing within the middleware */
typedef enum {
	SQ_CAT_EXEC_LOG = 0x1000,      /* Command execution data and metadata */
	SQ_CAT_EXEC_RESULT = 0x2000,  /* Command execution result output */
	SQ_CAT_HEARTBEAT = 0x3000,   /* Keep-alive for persistent connections */
	SQ_CAT_NOTIFY = 0x4000,     /* General notification message */
	SQ_CAT_UI = 0x5000,        /* Node UI Information */
	SQ_CAT_SYS_INFO = 0x7000, /* System metrics (CPU, Mem) for UI display */
	SQ_CAT_ERR_LOG = 0xE000, /* Standard error (stderr) output */

	SQ_TYPE_OVERVIEW = 0x2001,
	SQ_TYPE_GEOMETRY = 0x5001,    // Request for window shape calculation
} sq_packet_type_t;

/**
 * Main node `Overview` UI Content
 * Context information generated by the shell
 */
typedef struct {
	int id;
	int timestamp;
	char project_name[64];
	char working_dir[256];
	char command[256];
	char output[512];
	unsigned int size;
} sq_overview_content_t;

/* Common header for all IPC communication */
typedef struct {
	uint32_t magic;
	uint32_t type; /* sq_packet_type_t */
	size_t payload_size;
} sq_header_t;

typedef struct {
	sq_overview_content_t content;
} sq_body_t;

/* --- ShapeQuake Extended Payload Structures --- */

typedef struct {
	/* Basic execution state */
	sq_state_t state;
	pid_t foreground_pid;
	int master_fd;

	/* Static context for protocol headers */
	sq_overview_content_t saved_context; /* Inherited from shell and stored here */

	/* Progress calculation data: used in sq_executer_process_output */
	size_t output_buffer_size;  /* Discussed: Cumulative bytes from PTY */
	uint32_t line_count;        /* Discussed: Cumulative newlines from PTY */
	size_t expected_size;       /* Set by parser if total size is known */

	/* Terminal settings */
	struct termios orig_termios;
	bool is_raw;
} sq_runtime_context_t;

/**
 * Sub node Context
 * Middleware to Terminal
 * Attributes for node execution (Parsed from shell)
 */
typedef struct {
	uint32_t flags;       /* INTERACTIVE, LOCKED, etc */
	char shape_hint[32];  /* User specified geometry name */
	size_t cmd_len;       /* Length of command_line string */
	char command_line[];  /* Followed by the null-terminated command string */
} sq_payload_exec_t;

/**
 * Progress Metadata
 * Sent periodically within EXEC_RESULT or as a separate STATUS packet.
 */
typedef struct {
	double percentage;    /* 0.0 to 1.0 */
	uint64_t bytes_read;  /* Total bytes processed so far */
	uint32_t line_count;  /* Total lines processed */
	bool is_indeterminate;/* True if total size is unknown (e.g., tail -f) */
} sq_progress_t;

/**
 * Payload for SQ_TYPE_EXEC_RESULT
 * This is sent sequentially as data arrives from PTY.
 */
typedef struct {
	sq_progress_t progress;
	size_t chunk_size;    /* Size of the following data chunk */
	char data[];          /* Raw terminal output (VT100) */
} sq_payload_result_t;


#endif
